(define (problem transport-mad-bcn)
    (:domain transport)
    (:objects A1 A2 C1 C2 MAD BCN)
    (:init
        (Avio A1)
        (Avio A2)
        (Carrega C1)
        (Carrega C2)
        (Aeroport MAD)
        (Aeroport BCN)
        (A A1 MAD)
        (A A2 BCN)
        (A C1 MAD)
        (A C2 BCN))
    (:goal (and (A C1 BCN) (A C2 MAD))))  
