version: '3'

volumes:
  hdfs-simulat:
    name: "hadoop-dfs"
    driver: local

services:
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - hdfs-simulat:/opt/workspace
  
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - hdfs-simulat:/opt/workspace
  
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - hdfs-simulat:/opt/workspace
  
  spark-worker-3:
    image: spark-worker
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    volumes:
      - hdfs-simulat:/opt/workspace
  
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    volumes:
      - hdfs-simulat:/opt/workspace

